In [1]:
import numpy as np 
import pandas as pd

In [8]:
m_s = np.load('/Users/azeez/Documents/pose_estimation/DanceToMusicApp/ml/data/aist/motion_s2-2/train/gBR_sBM_c01_d04_mBR1_ch03_seg1.npy')
print(m_s.shape)

v_s = np.load("/Users/azeez/Documents/pose_estimation/DanceToMusicApp/ml/data/aist/video_s2-2/test/gBR_sBM_c01_d04_mBR0_ch02_seg1.npy")
print(v_s.shape)
vf = pd.DataFrame(v_s)
vf.head()

(120, 219)
(1, 2048)

,0,1,2,3,4,5,6,7,8,9,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
0,0.0,0.00072,0.039333,0.084106,0.493987,0.001909,0.015075,0.222686,0.073441,0.625134,...,0.073445,1.083901,0.485562,0.003379,0.389215,0.135357,0.032995,0.228132,0.749991,0.061202

In [5]:
m_s2 = np.load("/Users/azeez/Documents/pose_estimation/DanceToMusicApp/ml/data/aist/motion_s2-2/train/gBR_sBM_c01_d04_mBR1_ch03_seg4.npy")
print(m_s2.shape)

# show as a dataframe
df = pd.DataFrame(m_s)
df.head()

(120, 219)

,0,1,2,3,4,5,6,7,8,9,...,209,210,211,212,213,214,215,216,217,218
0,-0.044882,1.873663,-0.261025,0.988141,-0.005843,-0.153438,0.022850,0.993745,0.109314,0.151840,...,0.999977,0.999974,-0.007135,-0.000518,0.007136,0.999972,0.002273,0.000502,-0.002277,0.999997
1,-0.043471,1.878366,-0.259401,0.988539,-0.006782,-0.150812,0.022736,0.994284,0.104318,0.149242,...,0.999978,0.999974,-0.007207,0.000618,0.007205,0.999971,0.002382,-0.000635,-0.002377,0.999997
2,-0.042850,1.885763,-0.255745,0.990849,-0.010046,-0.134599,0.024154,0.994326,0.103596,0.132795,...,0.999979,0.999974,-0.007090,0.000974,0.007088,0.999973,0.002161,-0.000989,-0.002154,0.999997
3,-0.042745,1.893450,-0.251891,0.996245,-0.019287,-0.084404,0.029128,0.992710,0.116958,0.081533,...,0.999979,0.999978,-0.006594,0.000241,0.006593,0.999976,0.001908,-0.000254,-0.001906,0.999998
4,-0.042975,1.899550,-0.248113,0.999218,-0.032481,-0.022528,0.035177,0.990632,0.131951,0.018031,...,0.999979,0.999976,-0.006953,0.000248,0.006953,0.999974,0.001808,-0.000261,-0.001806,0.999998

### TikTok Dataset

In [9]:
tm1 = np.load("/Users/azeez/Documents/pose_estimation/DanceToMusicApp/ml/data/tik_tok_dataset/motion_s2/000000_0_0_seg1.npy")
print(tm1.shape)

tm1_df = pd.DataFrame(tm1)
tm1_df.head()

(60, 3, 25, 1)

ValueError: Must pass 2-d input. shape=(60, 3, 25, 1)